# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('room_number', models.CharField(max_length=50)),
                ('start_date', models.DateField(auto_now=True, db_index=True)),
                ('end_date', models.DateField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
